# .github/FUNDING.yml

github: Meldindavidsabu  
custom: 
  - 'https://github.com/sponsors/Meldindavidsabu'  # GitHub Sponsors link (Stripe)
  - 'upi://pay?pa=meldin.davidsabu@oksbi&pn=Meldin%20DavidSabu&cu=INR'  # Google Pay UPI link
